baseURL: ""
languageCode: en-us
title: Jimshu
paginate: 5
theme: PaperMod


params:
  #homeInfoParams:
  #  Title: "Hola !"
  #  Content: This is my new website
  
  ShowBreadCrumbs: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /teacup_nobg.png
    #favicon16x16: /teacup_nobg.png
    #favicon32x32: /teacup_nobg.png

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: 
    subtitle: 
    extrainfo:  !"
    imageUrl: me.jpeg
    imageWidth: 200
    imageHeight: 200
    imageTitle: Hola mfs !

  socialIcons:
    - name: github
      url: ""
    - name: Twitter
      url: "\"
    - name: Discord
      url: ""
    - name: email
      url: ""


menu:
  main:
    - identifier: home
      name: Home
      url: ""
      weight: 1
    -
      weight: 5
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    #- identifier: archives
    #  name: Archives
    #  url: /archives/
    #  weight: 15
    - identifier: mylogs
      name: My Logs
      url: /mylogs/
      weight: 15
    - identifier: misc
      name: Misc
      url: /misc/
      weight: 20
    #- identifier: tags
    #  name: Tags
    #  url: /tags/
    #  weight: 25
